/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    menus: Menu;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Edit like WordPress: open a page → Sections tab → Add Section blocks (Hero, Image, Services, FAQ…). Reorder blocks, then Save. Changes appear on the live site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path. Use "home" for homepage.
   */
  slug: string;
  /**
   * Sections tab controls live page content (WordPress-style blocks).
   */
  template: 'builder' | 'home' | 'guide';
  status: 'published' | 'draft';
  /**
   * Use CMS header & footer on this page
   */
  useSiteChrome?: boolean | null;
  /**
   * Hero, Image, Services, Steps, FAQ, Form, Custom HTML, etc. Upload images in Media first, or paste an image URL on the block.
   */
  sections?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            /**
             * Words inside the title to emphasize
             */
            highlight?: string | null;
            lede?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaLink?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaLink?: string | null;
            showCalculator?: boolean | null;
            showTrustPills?: boolean | null;
            /**
             * Upload from Media library
             */
            image?: (number | null) | Media;
            /**
             * Or paste an external image URL
             */
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Upload from Media library
             */
            image?: (number | null) | Media;
            /**
             * Or paste an external image URL
             */
            imageUrl?: string | null;
            alt?: string | null;
            caption?: string | null;
            size?: ('full' | 'wide' | 'medium') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            items?:
              | {
                  title: string;
                  description: string;
                  linkLabel?: string | null;
                  linkUrl?: string | null;
                  /**
                   * Upload from Media library
                   */
                  image?: (number | null) | Media;
                  /**
                   * Or paste an external image URL
                   */
                  imageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            items?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  title: string;
                  description: string;
                  /**
                   * Upload from Media library
                   */
                  image?: (number | null) | Media;
                  /**
                   * Or paste an external image URL
                   */
                  imageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  name: string;
                  /**
                   * Upload from Media library
                   */
                  image?: (number | null) | Media;
                  /**
                   * Or paste an external image URL
                   */
                  imageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banks';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  /**
                   * Upload from Media library
                   */
                  image?: (number | null) | Media;
                  /**
                   * Or paste an external image URL
                   */
                  imageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            showLeadForm?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaForm';
          }
        | {
            /**
             * HTML for long-form guide body.
             */
            html: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richContent';
          }
        | {
            html: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'customHtml';
          }
        | {
            heading?: string | null;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relatedLinks';
          }
      )[]
    | null;
  metaTitle: string;
  metaDescription: string;
  metaKeywords?: string | null;
  canonicalPath?: string | null;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroHighlight?: string | null;
  heroLede?: string | null;
  heroUpdated?: string | null;
  bodyHtml?: string | null;
  faqs?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedLinks?:
    | {
        label?: string | null;
        slug?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload images here, then pick them inside page Section blocks (Image, Hero, Services…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Build header, footer and extra navigation menus.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  name: string;
  location: 'header' | 'header-utility' | 'footer' | 'mobile' | 'custom';
  items?:
    | {
        label: string;
        linkType?: ('custom' | 'page' | 'anchor') | null;
        /**
         * e.g. /off-plan-mortgage-dubai or #contact
         */
        url?: string | null;
        page?: (number | null) | Page;
        openInNewTab?: boolean | null;
        children?:
          | {
              label: string;
              linkType?: ('custom' | 'page' | 'anchor') | null;
              /**
               * e.g. /off-plan-mortgage-dubai or #contact
               */
              url?: string | null;
              page?: (number | null) | Page;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * New accounts stay Pending until Super Admin approves them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Super Admin approves users and manages security. Admins manage content. Editors edit pages.
   */
  role: 'superadmin' | 'admin' | 'editor';
  /**
   * Only Super Admin can approve or reject. Pending users cannot log in.
   */
  approvalStatus: 'pending' | 'approved' | 'rejected';
  approvedAt?: string | null;
  approvedByEmail?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  template?: T;
  status?: T;
  useSiteChrome?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              lede?: T;
              primaryCtaLabel?: T;
              primaryCtaLink?: T;
              secondaryCtaLabel?: T;
              secondaryCtaLink?: T;
              showCalculator?: T;
              showTrustPills?: T;
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    linkLabel?: T;
                    linkUrl?: T;
                    image?: T;
                    imageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    imageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        banks?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    name?: T;
                    image?: T;
                    imageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    image?: T;
                    imageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaForm?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              showLeadForm?: T;
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              html?: T;
              id?: T;
              blockName?: T;
            };
        customHtml?:
          | T
          | {
              html?: T;
              id?: T;
              blockName?: T;
            };
        relatedLinks?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  canonicalPath?: T;
  heroEyebrow?: T;
  heroTitle?: T;
  heroHighlight?: T;
  heroLede?: T;
  heroUpdated?: T;
  bodyHtml?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedLinks?:
    | T
    | {
        label?: T;
        slug?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  items?:
    | T
    | {
        label?: T;
        linkType?: T;
        url?: T;
        page?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              linkType?: T;
              url?: T;
              page?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  approvalStatus?: T;
  approvedAt?: T;
  approvedByEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Logo, navigation style, CTAs and top bar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  style?: ('classic' | 'centered' | 'minimal') | null;
  sticky?: boolean | null;
  showTopBar?: boolean | null;
  topBarText?: string | null;
  showTicker?: boolean | null;
  showPhone?: boolean | null;
  /**
   * Primary header menu
   */
  menu?: (number | null) | Menu;
  logo?: (number | null) | Media;
  logoText?: string | null;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  ctaStyle?: ('primary' | 'outline' | 'hidden') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer columns, social links and legal copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  style?: ('columns' | 'simple' | 'compact') | null;
  logo?: (number | null) | Media;
  aboutText?: string | null;
  /**
   * Optional footer menu (flat links)
   */
  menu?: (number | null) | Menu;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('whatsapp' | 'instagram' | 'linkedin' | 'facebook' | 'x' | 'youtube') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  disclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Brand identity, contact details and ticker rates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Default site logo (header/footer can override).
   */
  logo?: (number | null) | Media;
  /**
   * Social share image (1200?630)
   */
  ogImage?: (number | null) | Media;
  /**
   * Brand primary (hex)
   */
  primaryColor?: string | null;
  /**
   * Accent / CTA green (hex)
   */
  accentColor?: string | null;
  phone: string;
  phoneHref: string;
  email: string;
  whatsappNumber: string;
  whatsappMessage?: string | null;
  addressLine?: string | null;
  tickerItems?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  footerDisclaimer: string;
  guideDisclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  style?: T;
  sticky?: T;
  showTopBar?: T;
  topBarText?: T;
  showTicker?: T;
  showPhone?: T;
  menu?: T;
  logo?: T;
  logoText?: T;
  ctaLabel?: T;
  ctaLink?: T;
  ctaStyle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  style?: T;
  logo?: T;
  aboutText?: T;
  menu?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  ogImage?: T;
  primaryColor?: T;
  accentColor?: T;
  phone?: T;
  phoneHref?: T;
  email?: T;
  whatsappNumber?: T;
  whatsappMessage?: T;
  addressLine?: T;
  tickerItems?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  footerDisclaimer?: T;
  guideDisclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}